# Generated by Django 4.0.4 on 2023-03-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_alter_customer_profile_pic_alter_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trouble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('フリーザー', 'フリーザー'), ('ロボット', 'ロボット'), ('コンベア', 'コンベア'), ('その他', 'その他')], max_length=200, null=True)),
            ],
        ),
    ]
