# Generated by Django 4.0.4 on 2023-03-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_trouble'),
    ]

    operations = [
        migrations.AddField(
            model_name='trouble',
            name='title',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
