# Generated by Django 4.0.4 on 2023-03-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0011_trouble_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parts',
            options={'verbose_name_plural': 'parts'},
        ),
        migrations.AlterModelOptions(
            name='trouble',
            options={'verbose_name_plural': 'trouble'},
        ),
        migrations.RenameField(
            model_name='trouble',
            old_name='category',
            new_name='main_category',
        ),
        migrations.AddField(
            model_name='trouble',
            name='note',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='trouble',
            name='sub_category',
            field=models.CharField(choices=[('インレット', 'インレット'), ('アウトレット', 'アウトレット'), ('ベルト', 'ベルト'), ('ロボット', 'ロボット'), ('コンベア', 'コンベア'), ('その他', 'その他')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trouble',
            name='trouble_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
