# Generated by Django 4.0.4 on 2023-03-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0014_bigcategory_smallcategory_alter_manual_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigcategory',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='smallcategory',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
