# Generated by Django 4.0.4 on 2023-03-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0016_category_alter_trouble_main_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trouble',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
